### PR TITLE
Update cloudberry backup hostname and reorganize images.

### PR DESCRIPTION
**Pull request by justinknierim**
Updated a single image with the new hostname, and moved the images from images/ to images/cloudberry-backup.

### CODE REVIEW

**Comment by squidboylan** [comment]
The article hierarchy we decided to use moving to the future, is to have a directory per article or app, so the hierarchy should be something like source/dreamobjects/tutorials/cloudberry/how-to-use-cloudberry-backup-with-dreamobjects.rst for the article, and source/dreamobjects/tutorials/cloudberry/images/*.png for the images, instead of images/cloudberry/*.png

**Comment by squidboylan** [comment]
We can discuss using the hierarchy you have in this commit if you would like

**Comment by justinknierim** [comment]
Interesting, I didn't hear any mention of changes like that.  I confirmed the dir rename with Justin first to make sure I didn't mess things up.  There should generally only be one article per a given software package, so having it in its own dir as well seems a bit unnecessary.  Hrm.

**Comment by squidboylan** [comment]
justinlunds other PR has the image organization the same as this commit's image organization, so i think we're all on the same page, merging

**Pull request merged**
