### PR TITLE
Trellis on DreamCompute document

### PR DESCRIPTION
**Pull request by jasperf**
Here is the Trellis on DreamCompute tutorial. Have a look see.

### CODE REVIEW

**Comment by squidboylan** [comment]
Hi Jasperf, thanks for the submission. There are some formatting issues with the document, please wrap lines at 80 characters (or less), fix the underlines of each title (some are too long or too short, they should be the same length as the text they underline), remove the trailing whitespace that can be found on some lines, finally, our build tool complains because you use "here" mutliple times as a link to different things, rst doesnt let you reuse text for different links, it's a weird limitation but it's there, so instead you can just link the url without putting it behind some text.

**Comment by squidboylan** [comment]
Your article looks very interesting, I'm gonna follow the steps and then I'll let you know if there are any tweaks i think should be made. Thanks again for the submission :)

**Comment by squidboylan** [comment]
I seem to be having trouble setting up a local development environment. I've tried `vagrant up` in the trellis dir and also running `./deploy.sh` and `ansible-playbook dev.yml`, but all seem to fail. Your article describes how to configure your development environment well, but it seems to be missing the command to start the vms locally.

**Comment by jasperf** [comment]
I added more information. I wonder if you cloned Trellis en Bedrock and configured all files under group_vars/development and then installed the Andible Galaxy roles and the did a Vagrant up.

**Comment by squidboylan** [comment]
I was able to use the guide to install lemp and wordpress on some vms, it is pretty easy and convenient. I think my issue initially was having the wrong versions of the required software, but I fixed that (I should have paid more attention), but totally not the fault of the article. There seems to still be some lines that are over 80 lines and some whitespace at the end of some lines. Other than that your article looks pretty good and I was able to follow it to use trellis properly. Thanks again

**Comment by squidboylan** [comment]
I will fix the line wraps and ending whitespace, and squash into one commit and merge, thanks again :+1

**Comment by squidboylan** [comment]
this has been merged, https://github.com/dreamhost/dreamcloud-docs/commit/159333b21039d6b4017b70af945b93716a006649 is the commit. Github doesnt think it was merged because i squashed the commits, but it was merged. https://help.dreamhost.com/hc/en-us/articles/221172468-Step-by-step-guide-to-set-up-Trellis-on-DreamCompute is the published article. Thanks again :)

**Pull request closed without merging**
