### PR TITLE
Dreamcompute mount volumes

### PR DESCRIPTION
**Pull request by justinknierim**
This shows how to check volume storage quota, create a volume, attach it, make a file system, and mount it automatically via fstab. There are existing documents describing the difference between ephemeral and volumes, and a "cli cheat sheet" (https://help.dreamhost.com/hc/en-us/articles/215912758-DreamCompute-command-line-interface-cheat-sheet) that are only vaguely related. I think this will help.

Re-upped since reorganizing with help of Justin Lund.  It was discussed to not use cinder and nova but openstack CLI instead, but we have no current documents with it right now.

### CODE REVIEW

**Comment by squidboylan** [comment]
lgtm :+1:

**Comment by squidboylan** [comment]
Actually, could you change the title to be down cased? That's something I've been trying follow more often because the wiki team is doing it and I'd like to remain consistent across the KB. Down casing means you only capitalize the first word in a title and any proper nouns, in this case it would be "How to create and mount volumes on DreamCompute". Thanks

**Comment by justinknierim** [comment]
Sure thing, title updated.  Good to know a standard for these things for the future.  :)

**Comment by squidboylan** [comment]
Thanks, merging

**Pull request merged**
