### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by squidboylan**
Make it possible to use the "only" directive in our docs

### CODE REVIEW

**Comment by smaffulli** [comment]
why did you make build script invisible?

**Comment by squidboylan** [comment]
I did that because you really shouldnt be running the build script outside of tox, so I dont want people to see it and run it, I want people to just use tox, which will then run the script

**Comment by drwahl** [comment]
A common convention (in a few different projects) is to prepend "_" to the script to denote that it isn't really intended to be called directly.  Whether or not the script should be hidden is still debatable, but if it shouldn't be called directly, I think it should be prepended with "_".

**Comment by squidboylan** [comment]
Stef and I have discussed this a bit and are not sure it's worth the extra hassle to be able to use the "only" directive in our docs

**Comment by smaffulli** [comment]
Let's abandon this, as we decided we're not going to use it.

**Pull request closed without merging**
